# POST http://localhost:5001/api/job/search
# Content-Type: application/json

# {
#   "KeyWords": "Data Engineer",
#   "JobCategory": "Technology and IT",
#   "JobType" : "Full-time"
# }


POST http://localhost:5001/api/subscribe
Content-Type: application/json

{
  "email": "unekwuojoabah4@gmail.com"
 
}